### PR TITLE
Vision

### LINKED ISSUE #374: New article: Vision (company or team or product vision)
# Title: Vision

- [x] What is this about: “What is this practice about”? Which existing (or new) problems does this practice solve? 

It's about motivating people, product development, and development itself by a company/product/team vision. What's vision and how it drives motivation or team to better alignment with a purpose.

- [x] Read more here: The starting point for your research (You can use different sources if you have better ones)

- https://www.productboard.com/blog/write-product-vision/
- https://examples.yourdictionary.com/best-examples-of-a-vision-statement.html
- https://www.businessnewsdaily.com/3882-vision-statement.html
- https://www.scrum.org/resources/blog/10-tips-product-owners-product-vision

- [x] Pick the corresponding labels: 
    - Stage:research
    - **Stage:building_team**
    - **Stage:development**
    - Stage:launch
    - Stage:maintenance
    - Stage:phase_out

## How to contribute:
- Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

### PR DESCRIPTION
**Pull request by fanatiicx**
Closes #374 

## If an article related PR

- [x ] I have checked that my suggestion follows the Contribution guide

- [x ]  I have added which issue this PR closes

- [x ] I have 0 warnings from Danger.js

- [x ] If I have added images, they are in /files/ folder

## If other PR

- [ ] I have added which issue this PR closes

### CODE REVIEW

**Comment by fanatiicx** [comment]
I wrote about company, team, and product vision (divided into these sections throughout the article). Happy to hear any feedback or suggestions for improvement. Thanks!

**Review by prokopsimek — CHANGES_REQUESTED** [review]
@fanatiicx Thank you for the article! I have to say you exceeded my expectations! 👏 I just have a few comments about the structure and the picture.

Please take a look at my suggestions and let's discuss them. :)

Každopádně - můžete mi dát nějaké kontaktní údaje na vás? Napište mi na [LinkedIn](https://www.linkedin.com/in/prokopsimek/) nebo e-mail (prokop@dxheroes.io), díky! :)

**Comment by fanatiicx** [comment]
@prokopsimek Thanks for your suggestions! :) They've been added. I added a bit of text about Amazon as an example. 

Let me know if the image is too big and I will resize it. Perhaps it's better to remove it if it distracts from the text examples of vision statements?

I'll reach out on LinkedIn or via email soon.

**Review by prokopsimek — APPROVED** [review]
@fanatiicx It's just awesome! 👏 Thank you!

**Comment by prokopsimek** [comment]
Published! https://developerexperience.io/practices/vision

I'll add some CSS styles for company vision quotes later this week.

**Pull request merged**
