### PR TITLE
added gradle

### LINKED ISSUE #268: Update article: Package management
- [x] Link to practice: "https://developerexperience.io/practices/package-management"

- [x] What is this about: "Add Java Specifying dependencies (Maven or Gradle)"

## How to contribute:
- Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

### PR DESCRIPTION
**Pull request by wilsantow**
Closes #268 

## If an article related PR

- [x] I have checked that my suggestion follows the Contribution guide

- [x]  I have added which issue this PR closes

- [x] I have 0 warnings from Danger.js

- [x] If I have added images, they are in /files/ folder

## If other PR

- [ ] I have added which issue this PR closes

### CODE REVIEW

**Review by prokopsimek — APPROVED** [review]
@wilsantow Thank you! 👏

**Review by ridlees — APPROVED** [review]
🎉 Thanks @wilsantow for your first contribution! 🎉

**Comment by wilsantow** [comment]
My pleasure @prokopsimek @ridlees

**Comment by ridlees** [comment]
@wilsantow If you want, you can continue the open source journey with us. There are some issues (good-first-issues) that you could try out. @prokopsimek or I will be here to help you with the next steps. How does that sound to you?

**Comment by wilsantow** [comment]
Hey, @ridlees I would be happy to collaborate. I am willing to write articles but I don't have major experience with it. If you or @prokopsimek  can give suggestions and feedback along the way, I am ready to work on other issues.

**Comment by ridlees** [comment]
@wilsantow We would be happy to do so. @Petr895 and I (Martin) are here to help you with the writing process. @prokopsimek @zeman-j4 are great guys you can approach with any question and I am sure that they will do their best to help you. 😄

**Pull request merged**
