### PR TITLE
smoketest_se

### PR DESCRIPTION
**Pull request by Harsha-Ambati**
Closes #[issue number]

## If an article related PR

- [ ] I have checked that my suggestion follows the Contribution guide

- [ ]  I have added which issue this PR closes

- [ ] I have 0 warnings from Danger.js

- [ ] If I have added images, they are in /files/ folder

## If other PR

- [ ] I have added which issue this PR closes

### CODE REVIEW

**Review by prokopsimek — CHANGES_REQUESTED** [review]
@Harsha-Ambati Hi! Thank you for your first PR. Have you missed changing an article content?

**Comment by Harsha-Ambati** [comment]
no! i just added an image

**Comment by prokopsimek** [comment]
@Harsha-Ambati Thank you for the image but is there any other intention to add it to any article? E.g. the Smoke Testing article?

**Comment by Harsha-Ambati** [comment]
yes! if article is already there ..i can add it..but I did not found the article

**Comment by Harsha-Ambati** [comment]
Can i add it now if possible?

**Comment by prokopsimek** [comment]
@Harsha-Ambati The article in the Knowledgebase is here: https://developerexperience.io/practices/smoke-testing

Ohh, you have just found it! 👏

May I ask you why you propose the change of the image?

**Comment by Harsha-Ambati** [comment]
i have added it to smoke test article..done :)

**Comment by Harsha-Ambati** [comment]
iam not changing the image..i just added extra image to article

**Comment by prokopsimek** [comment]
@Harsha-Ambati Thanks, but what it should be describing? Why do you think that it's necessary to add it to the article? 🙂

**Comment by Harsha-Ambati** [comment]
i found it is useful :) soory if I am wrong

**Comment by Harsha-Ambati** [comment]
iam particpating in hacktoberfest ..i found your repo in digital ocean websites..so I made a pull request

**Comment by prokopsimek** [comment]
@Harsha-Ambati Thank you! I'll ask my colleagues what they think about it. 👍

**Comment by DominikMilaniak** [comment]
@Harsha-Ambati Hello Harsha, we don't know each other yet - I'm Dominic 😄 We are super excited about your pull request and we are humbled you chose one of our repositories to contribute to during Hacktoberfest 2020 🥳 One little note I have - Hacktoberfest's motto is "Quantity is fun, quality is key". There are also some [Quality Standards](https://hacktoberfest.digitalocean.com/details#quality) every contributor should follow. We are happy, that you are contributing to open source and especially to our projects, but please keep Quality Standards in mind as by the rules of Hacktoberfest, you might not be eligible for their rewards, if you will not follow them. Thank you for your understanding, thank you for choosing us and thank you for contributing to open source! Happy Hacking! 🥳

**Comment by prokopsimek** [comment]
So be it!

**Comment by ridlees** [comment]
@Harsha-Ambati Hello Harsha, if you are still interested in contributing to our repo, there are Hactoberfest approved issues you can try. Give them a [look](https://github.com/DXHeroes/knowledge-base-content/issues?q=is%3Aissue+is%3Aopen+label%3A%22Difficulty%3A+Low%22), and let me know if there is something you find interesting. Based on your interest in CyberSecurity, you could also look at [What to do when my App gets hacked?](https://github.com/DXHeroes/knowledge-base-content/issues/117). I wish you a great day.

**Pull request closed without merging**
